version: "3.4"

networks:
  code-network:
    driver: bridge

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - code-network

  nginx-alpine:
    image: nginx:alpine
    container_name: nginx-alpine
    restart: always
    tty: true
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=cbor-project.local
    networks:
      - code-network

  php-alpine:
    container_name: php-alpine
    restart: always
    tty: true
    links:
      - nginx-alpine
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - code-network